config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'healthcheck', to: 'healthcheck#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  scope ':locale', locale: /#{I18n.available_locales.join('|')}/ do
    authenticated :user do
      resources :artists
      resources :deal_types
      resources :ticket_sale_options
      resources :tours
      resources :venues, except: %i[index show]
    end

    resources :venues, only: %i[index show] # unauthenticated visitors only have index & show routes
  end

  root to: redirect("/#{I18n.default_locale}")
  mount BetterTogether::Engine => '/'
end

app/models/journey_stage.rb
# frozen_string_literal: true

class JourneyStage < BetterTogether::Category
  has_many :journey_stage_topics, -> { positioned }, dependent: :destroy
  has_many :topics, through: :journey_stage_topics
end

app/models/topic.rb
# frozen_string_literal: true

class Topic < BetterTogether::Category
  has_many :journey_stage_topics, -> { positioned }, dependent: :destroy
  has_many :journey_stages, through: :journey_stage_topics
end

app/views/shared/_new_to_nl_category_fields.html.erb
<%# locals: (model:, form:)%>

<div class="row row-cols-2 new-to-nl-category-fields">
  <div class="col mb-3 pb-3 border-bottom">
    <%= required_label form, :journey_stages %>
    <%= form.select :journey_stage_ids, options_from_collection_for_select(JourneyStage.positioned.all.includes(:string_translations), :id, :name, model.journey_stage_ids), { include_blank: true, multiple: true }, class: 'form-select' %>
    <small class="form-text text-muted"><%= t('hints.journey_stages.select_multiple') %></small>
  </div>

  <div class="col mb-3 pb-3 border-bottom">
    <%= form.label :topics, class: 'form-label' %>
    <%= form.select :topic_ids, options_from_collection_for_select(Topic.positioned.all.includes(:string_translations), :id, :name, model.topic_ids), { include_blank: true, multiple: true }, class: 'form-select' %>
    <small class="form-text text-muted"><%= t('hints.topics.select_multiple') %></small>
  </div>
</div>